# SPDX-License-Identifier: BUSL-1.1

development: true
logger:
  encoder: console
  level: debug
cmd/santa:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 443
    certPath: cmd/santa/.testdata/localhost.crt
    keyPath: cmd/santa/.testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
cmd/santa-sleigh:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 1443
    certPath: cmd/santa-sleigh/.testdata/localhost.crt
    keyPath: cmd/santa-sleigh/.testdata/localhost.key
  initialBadges:
    - name: Ice Breaker
      type: SOCIAL
      leftProgressInterval: 0
      rightProgressInterval: 3
    - name: Trouble maker
      type: SOCIAL
      leftProgressInterval: 4
      rightProgressInterval: 9
achievements:
  db:
    spaces:
      - BADGES
    urls:
      - localhost:3301
    user: admin
    password: pass
  messageBroker:
    #It's not used, because we`re not consuming anything in the production code.
    #So, its configured here just for testing or other local purposes.
    urls:
      - localhost:9094