# SPDX-License-Identifier: BUSL-1.1

development: true
logger:
  encoder: console
  level: info
cmd/santa:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 443
    certPath: cmd/santa/.testdata/localhost.crt
    keyPath: cmd/santa/.testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
cmd/santa-sleigh:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 2443
    certPath: cmd/santa-sleigh/.testdata/localhost.crt
    keyPath: cmd/santa-sleigh/.testdata/localhost.key
achievements:
  levels:
    agendaReferrals:
      - 10
      - 5
      - 1
    consecutiveMiningSessions:
      - 90
      - 60
      - 30
      - 10
      - 5
      - 1
  tasks:
    T1Referrals: 5
  db:
    spaces:
      - GLOBAL
      - USER_PROGRESS
      - BADGES
      - ACHIEVED_USER_BADGES
      - LEVELS
      - ACHIEVED_USER_LEVELS
      - TASKS
      - ACHIEVED_USER_TASKS
      - CURRENT_USER_ROLES
      - AGENDA_REFERRALS
    urls:
      - localhost:3301
    user: admin
    password: pass
  messageBroker:
    consumerGroup: santa-local
    createTopics: true
    urls:
      - localhost:9092
    topics:
      - name: achievements-tasks
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: achievements-badges
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: achievements-progress
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: achievements-agenda-referrals
        partitions: 10
        replicationFactor: 1
        retention: 1000h
        ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-events
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: economy-mining
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - users-events # user creation, modification and deletion events
      - economy-mining # start mining events
      - achievements-tasks # achieved tasks by the user
      - achievements-badges # achieved badges by the user
      - achievements-progress # user_progress updates
      - achievements-agenda-referrals # count of users referred from agenda changed