# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: info
cmd/santa:
  host: localhost:6443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 6443
    certPath: cmd/santa/.testdata/localhost.crt
    keyPath: cmd/santa/.testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
  wintr/auth/ice:
    jwtSecret: bogus
cmd/santa-sleigh:
  host: localhost:7443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 7443
    certPath: cmd/santa-sleigh/.testdata/localhost.crt
    keyPath: cmd/santa-sleigh/.testdata/localhost.key
  wintr/auth/ice:
    jwtSecret: bogus
tasksList: &tasksList
  - type: claim_username
    prize: 100
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/nikename.svg
  - type: start_mining
    prize: 200
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/mining.svg
  - type: upload_profile_picture
    prize: 300
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/profile-waiting.svg
  - type: follow_us_on_twitter
    prize: 400
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/twitter-follow.svg
    url: https://x.com/ice_blockchain
  - type: join_telegram
    prize: 500
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/join-telegram-waiting.svg
    url: https://t.me/iceblockchain
  - type: invite_friends
    prize: 600
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/invite.svg
friends-invited: &friends-invited
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5432/santa
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5432/santa
  messageBroker: &friendsInvitedMessageBroker
    consumerGroup: friends-invited-testing
    createTopics: true
    urls:
      - localhost:9092
    topics: &friendsInvitedMessageBrokerTopics
      - name: santa-health-check
        partitions: 1
        replicationFactor: 1
      - name: friends-invited
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: users-table
friends-invited_test:
  <<: *friends-invited
  messageBroker:
    <<: *friendsInvitedMessageBroker
    consumingTopics: *friendsInvitedMessageBrokerTopics
    consumerGroup: santa-local-friends-invited-test
badges: &badges
  levels:
    - name: Wave Starter
      toInclusive: 1
    - name: Beach Walker
      fromInclusive: 2
      toInclusive: 3
    - name: Rhythm Keeper
      fromInclusive: 4
      toInclusive: 5
    - name: Dance Captain
      fromInclusive: 6
      toInclusive: 7
    - name: Vibe Master
      fromInclusive: 8
      toInclusive: 9
    - name: Festival Guru
      fromInclusive: 10
  coins:
    - name: Rookie Raver
      toInclusive: 10
    - name: Beats Saver
      fromInclusive: 20
      toInclusive: 30
    - name: Tune Tracker
      fromInclusive: 40
      toInclusive: 50
    - name: Rhythm Collector
      fromInclusive: 60
      toInclusive: 70
    - name: Bass Booster
      fromInclusive: 80
      toInclusive: 90
    - name: Melody Maker
      fromInclusive: 100
      toInclusive: 110
    - name: Harmony Holder
      fromInclusive: 120
      toInclusive: 130
    - name: Sound Seeker
      fromInclusive: 140
      toInclusive: 150
    - name: Vibe Crafter
      fromInclusive: 160
      toInclusive: 170
    - name: Festival Icon
      fromInclusive: 180
  socials:
    - name: Meet Greeter
      toInclusive: 1
    - name: Friend Finder
      fromInclusive: 2
      toInclusive: 3
    - name: Party Starter
      fromInclusive: 4
      toInclusive: 5
    - name: Crowd Mixer
      fromInclusive: 6
      toInclusive: 7
    - name: Dance Circle King
      fromInclusive: 8
      toInclusive: 9
    - name: Wave Rider
      fromInclusive: 10
      toInclusive: 11
    - name: Night Owl
      fromInclusive: 12
      toInclusive: 13
    - name: Beach Buddy
      fromInclusive: 14
      toInclusive: 15
    - name: Sunset Chaser
      fromInclusive: 16
      toInclusive: 17
    - name: Dance Floor Legend
      fromInclusive: 18
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5432/santa
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5432/santa
  messageBroker: &badgesMessageBroker
    consumerGroup: badges-testing
    createTopics: true
    urls:
      - localhost:9092
    topics: &badgesMessageBrokerTopics
      - name: santa-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: try-achieve-badges-commands
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: achieved-badges
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: completed-levels
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: balances-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: global-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: friends-invited
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: try-achieve-badges-commands
      - name: achieved-badges
      - name: users-table
      - name: completed-levels
      - name: balances-table
      - name: global-table
      - name: friends-invited
badges_test:
  <<: *badges
  messageBroker:
    <<: *badgesMessageBroker
    consumingTopics: *badgesMessageBrokerTopics
    consumerGroup: santa-local-badges-test
tasks: &tasks
  tasksV2Enabled: false
  requiredFriendsInvited: 5
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5432/santa
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5432/santa
  messageBroker: &tasksMessageBroker
    consumerGroup: tasks-testing
    createTopics: true
    urls:
      - localhost:9092
    topics: &tasksMessageBrokerTopics
      - name: santa-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: try-complete-tasks-commands
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: completed-tasks
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: mining-sessions-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: friends-invited
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: try-complete-tasks-commands
      - name: users-table
      - name: mining-sessions-table
      - name: friends-invited
  tasksList: *tasksList
  tenantName: sunwaves
tasks_test:
  <<: *tasks
  messageBroker:
    <<: *tasksMessageBroker
    consumingTopics: *tasksMessageBrokerTopics
    consumerGroup: santa-local-tasks-test
levels-and-roles: &levels-and-roles
  tasksV2Enabled: false
  requiredInvitedFriendsToBecomeAmbassador: 3
  roleNames:
    - Snowman
    - Ambassador
  miningStreakMilestones:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
  completedTasksMilestones:
    6: 1
    7: 2
    8: 3
    9: 4
    10: 5
    11: 6
  agendaContactsJoinedMilestones:
    12: 0
    13: 1
    14: 2
    15: 3
  pingsSentMilestones:
    16: 1
    17: 2
    18: 3
    19: 4
    20: 5
    21: 6
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5432/santa
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5432/santa
  tasksList: *tasksList
  messageBroker: &levels-and-rolesMessageBroker
    consumerGroup: levels-and-roles-testing
    createTopics: true
    urls:
      - localhost:9092
    topics: &levels-and-rolesMessageBrokerTopics
      - name: santa-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: try-complete-levels-commands
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: completed-levels
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: enabled-roles
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: mining-sessions-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: started-days-off
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: completed-tasks
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: user-pings
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: friends-invited
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: contacts-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: try-complete-levels-commands
      - name: users-table
      - name: mining-sessions-table
      - name: started-days-off
      - name: completed-tasks
      - name: user-pings
      - name: friends-invited
      - name: contacts-table
levels-and-roles_test:
  <<: *levels-and-roles
  messageBroker:
    <<: *levels-and-rolesMessageBroker
    consumingTopics: *levels-and-rolesMessageBrokerTopics
    consumerGroup: santa-local-levels-and-roles-test