# SPDX-License-Identifier: BUSL-1.1

development: true
logger:
  encoder: console
  level: debug
cmd/santa:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 443
    certPath: cmd/santa/.testdata/localhost.crt
    keyPath: cmd/santa/.testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
cmd/santa-sleigh:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 1443
    certPath: cmd/santa-sleigh/.testdata/localhost.crt
    keyPath: cmd/santa-sleigh/.testdata/localhost.key
achievements:
  db:
    spaces:
      - BADGES
    urls:
      - localhost:3301
    user: admin
    password: pass
  messageBroker:
    consumerGroup: santa-local
    createTopics: true
    urls:
      - localhost:9094
    consumingTopics:
      - users-events # user creation and deletion events
      - economy-events # start/stop mining events