# SPDX-License-Identifier: BUSL-1.1

basePath: /v1
definitions:
  achievements.Task:
    properties:
      completedAt:
        example: "2022-01-03T16:20:52.156534Z"
        type: string
      index:
        example: 0
        type: integer
      name:
        example: TASK1
        type: string
      userId:
        example: did:ethr:0x4B73C58370AEfcEf86A6021afCDe5673511376B2
        type: string
    type: object
  main.RequestCompleteTask:
    properties:
      completedAt:
        example: "2022-01-03T16:20:52.156534Z"
        type: string
      index:
        example: 0
        type: integer
      name:
        example: TASK1
        type: string
      userId:
        example: did:ethr:0x4B73C58370AEfcEf86A6021afCDe5673511376B2
        type: string
    type: object
  server.ErrorResponse:
    properties:
      code:
        example: SOMETHING_NOT_FOUND
        type: string
      data:
        additionalProperties: true
        type: object
      error:
        example: something is missing
        type: string
    type: object
info:
  contact:
    name: ice.io
    url: https://ice.io
  description: API that handles everything related to write operations for user's
    achievements(badges, levels, roles, task completions, etc).
  title: User Achievements API
  version: latest
paths:
  /user-achievements/{userId}/tasks:
    post:
      consumes:
      - application/json
      description: Completes a specific task for the user.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the user
        in: path
        name: userId
        required: true
        type: string
      - description: Request params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.RequestCompleteTask'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/achievements.Task'
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "403":
          description: if not allowed
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "404":
          description: if user not found
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "409":
          description: if task already completed
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Achievements
  /user-achievements/{userId}/tasks/{taskName}:
    delete:
      consumes:
      - application/json
      description: Un-Completes a specific task for the user.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the user
        in: path
        name: userId
        required: true
        type: string
      - description: The name of the task
        in: path
        name: taskName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok - uncompleted
        "204":
          description: already uncompleted
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "403":
          description: if not allowed
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Achievements
schemes:
- https
swagger: "2.0"
