# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: info
tasksList: &tasksList
  - type: claim_username
    prize: 100
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/nikename.svg
  - type: start_mining
    prize: 200
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/mining.svg
  - type: upload_profile_picture
    prize: 300
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/profile-waiting.svg
  - type: follow_us_on_twitter
    prize: 400
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/twitter-follow.svg
    url: https://x.com/ice_blockchain
  - type: join_telegram
    prize: 500
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/join-telegram-waiting.svg
    url: https://t.me/iceblockchain
  - type: invite_friends
    prize: 600
    icon: https://app.sunwavestoken.com/web/images/Components/Overview/invite.svg
tasks: &tasks
  tasksV2Enabled: false
  requiredFriendsInvited: 5
  db: &tasksDatabase
    urls:
      - localhost:3302
    user: admin
    password: pass
  messageBroker: &tasksMessageBroker
    consumerGroup: tasks-testing
    createTopics: true
    urls:
      - localhost:9093
    topics: &tasksMessageBrokerTopics
      - name: santa-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: try-complete-tasks-commands
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: completed-tasks
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: mining-sessions-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: friends-invited
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: try-complete-tasks-commands
      - name: users-table
      - name: mining-sessions-table
      - name: friends-invited
  tasksList: *tasksList
  tenantName: sunwaves
tasks_test:
  <<: *tasks
  messageBroker:
    <<: *tasksMessageBroker
    consumingTopics: *tasksMessageBrokerTopics
    consumerGroup: santa-testing-tasks
  db:
    <<: *tasksDatabase
    schemaPath: tasks/DDL.lua
