// Package api GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "ice.io",
            "url": "https://ice.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user-achievements/{userId}": {
            "get": {
                "description": "Returns the achievements for an user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the user",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "You can include any of [` + "`" + `TASKS` + "`" + `,` + "`" + `BADGES` + "`" + `].",
                        "name": "includeCollectibles",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/achievements.UserAchievements"
                        }
                    },
                    "400": {
                        "description": "if validations fail",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "if not authorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "if user not found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "if syntax fails",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user-achievements/{userId}/badges": {
            "get": {
                "description": "Returns the badges for an user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievements"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the user",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The type of the badges you want. It can be ` + "`" + `LEVEL` + "`" + `, ` + "`" + `SOCIAL` + "`" + ` or ` + "`" + `ICE` + "`" + `",
                        "name": "badgeType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/achievements.BadgeInventory"
                            }
                        }
                    },
                    "400": {
                        "description": "if validations fail",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "if not authorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "if user requests badges of the another user",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "if user not found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "if syntax fails",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "achievements.BadgeInventory": {
            "type": "object",
            "properties": {
                "achieved": {
                    "type": "boolean",
                    "example": false
                },
                "globalAchievementPercentage": {
                    "description": "The percentage of all the users that have this badge.",
                    "type": "number",
                    "example": 25.5
                },
                "interval": {
                    "$ref": "#/definitions/badges.ProgressInterval"
                },
                "name": {
                    "type": "string",
                    "example": "ICE Breaker"
                },
                "type": {
                    "type": "string",
                    "example": "SOCIAL"
                }
            }
        },
        "achievements.BadgeOverview": {
            "type": "object",
            "properties": {
                "interval": {
                    "$ref": "#/definitions/badges.ProgressInterval"
                },
                "name": {
                    "type": "string",
                    "example": "ICE Breaker"
                },
                "position": {
                    "type": "object",
                    "properties": {
                        "outOf": {
                            "type": "integer",
                            "example": 10
                        },
                        "x": {
                            "type": "integer",
                            "example": 3
                        }
                    }
                },
                "type": {
                    "type": "string",
                    "example": "SOCIAL"
                }
            }
        },
        "achievements.TaskTODO": {
            "type": "object",
            "properties": {
                "achieved": {
                    "type": "boolean",
                    "example": false
                },
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "name": {
                    "type": "string",
                    "example": "CLAIM_USERNAME"
                }
            }
        },
        "achievements.UserAchievements": {
            "type": "object",
            "properties": {
                "badges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/achievements.BadgeOverview"
                    }
                },
                "level": {
                    "type": "integer",
                    "example": 11
                },
                "role": {
                    "type": "string",
                    "example": "AMBASSADOR"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/achievements.TaskTODO"
                    }
                }
            }
        },
        "badges.ProgressInterval": {
            "type": "object",
            "properties": {
                "left": {
                    "type": "integer",
                    "example": 11
                },
                "right": {
                    "type": "integer",
                    "example": 22
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "SOMETHING_NOT_FOUND"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "error": {
                    "type": "string",
                    "example": "something is missing"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "latest",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{"https"},
	Title:            "User Achievements API",
	Description:      "API that handles everything related to read only operations for user's achievements(badges, levels, roles, task completions, etc).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
